[package]
name = "hermit-bench"
authors = ["Carl Wachter <carl.wachter@rwth-aachen.de>"]
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
inventory = "0.3"
serde_json = "1.0"
regex = "1.10.5"